#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright Lee Begg 2009
#
# 3news video download tool
# Licence: GPL v2 or later

import re
import sys
from viddl.steps import download_step, extract_step, http_download_video_step

const_video_url_param_re = re.compile(r'var video ="([^"]+)"')
const_video_url_real_fmt = "http://flash.mediaworks.co.nz/tv3/streams/_definst_%s_%s.mp4"
video_speed = "330K"


if(len(sys.argv) > 1):
    req_url = sys.argv[1]
    
else:
    print("Usage: %s url" % sys.argv[0])
    sys.exit(1)
    

#should check url first
video_url = req_url

video_webpage = download_step(True, 'Retrieving video webpage', 'unable to retrieve video webpage', video_url)

video_url_param = extract_step('Extracting video URL parameter', 'unable to extract video URL parameter', const_video_url_param_re, video_webpage)

print "raw video_url_param: ", video_url_param

if video_url_param[0] != '/':
    video_url_param = video_url_param.replace(video_url_param[0], '/')
else:
    video_url_param = video_url_param.replace('*', '/')

if video_url_param[:2] == '//':
    video_url_param = video_url_param[1:]

video_url_real = const_video_url_real_fmt % (video_url_param, video_speed)

video_filename = video_url_real.split('/')[-1]

print video_url_real

http_download_video_step(video_filename, video_url_real)


# Finish
sys.exit()

