#!/usr/bin/env python
# Copyright Lee Begg 2009
#
# 3news video download tool
#
# Borrowing heavily from youtube-dl


import sys
import re
from viddl.steps import download_step, http_download_video_step, extract_step


const_video_url_param_re = re.compile(r'flashvars="file=([^&]+)&')
const_video_url_real_fmt = "%s"



if(len(sys.argv) > 1):
    req_url = sys.argv[1]
    
else:
    print("Usage: %s url" % sys.argv[0])
    sys.exit(1)
    

#should check url first
video_url = req_url

video_webpage = download_step(True, 'Retrieving video webpage', 'unable to retrieve video webpage', video_url)

video_url_param = extract_step('Extracting video URL parameter', 'unable to extract video URL parameter', const_video_url_param_re, video_webpage)
video_url_real = const_video_url_real_fmt % video_url_param

video_filename = video_url_real.split('/')[-1]

http_download_video_step(video_filename, video_url_real)
# Finish
sys.exit()

