#!/usr/bin/env python
# Copyright Lee Begg 2009
#
# NZ Herald video download tool
# Licence: GPL v2 or later


import sys
import re
import urllib2
from viddl.steps import download_step, extract_step, download_video_step



const_xmlstring_re = re.compile(r'xmlstring : "([^"]+)"')
const_video_url_param_re = re.compile(r'.*<media_gallery><media type="video" url="http://([^"]+)"><title><.*')
const_video_url_real_fmt = "http://%s"




if(len(sys.argv) > 1):
    req_url = sys.argv[1]
    
else:
    print("Usage: %s url" % sys.argv[0])
    sys.exit(1)
    

#should check url first
video_url = req_url

video_webpage = download_step(True, 'Retrieving video webpage', 'unable to retrieve video webpage', video_url)

xmlquotedstr = extract_step('Extracting quoted XML', 'unabled to extract quoted XML', const_xmlstring_re, video_webpage)
xmlstr = urllib2.unquote(xmlquotedstr)

print
print xmlstr
print

video_url_param = extract_step('Extracting video URL parameter', 'unable to extract video URL parameter', const_video_url_param_re, xmlstr)

video_url_param = urllib2.quote(video_url_param)

video_url_real = const_video_url_real_fmt % (video_url_param)

print video_url_real

video_filename = video_url_real.split('/')[-1]

download_video_step(video_filename, video_url_real)

# Finish
sys.exit()

