#!/usr/bin/env python
# Copyright Lee Begg 2009
#
# NZ On Screen video download tool
#
# Licence: GPL v2 or later


import sys
import re
from xml.etree import ElementTree as ET
from viddl.steps import download_step, extract_step, download_video_step

const_xmlfile_re = re.compile(r"flashVars.*=.*'.*&amp;xmlURL=([^']+)';")
const_xmlfile_url_fmt = "http://www.nzonscreen.com%s"



if(len(sys.argv) > 1):
    req_url = sys.argv[1]
    
else:
    print("Usage: %s url" % sys.argv[0])
    sys.exit(1)
    

#should check url first
video_url = req_url

video_webpage = download_step(True, 'Retrieving video webpage', 'unable to retrieve video webpage', video_url)

xmlfilestr = extract_step('Extracting XML playlist url', 'unabled to extract XML playlist url', const_xmlfile_re, video_webpage)

xmlfileurl = const_xmlfile_url_fmt % xmlfilestr

xml_file = download_step(True, 'Retrieving XML playlist', 'unable to retrieve XML playlist', xmlfileurl)

print('Parsing XML')

xmldoc = ET.fromstring(xml_file)

print('Extracting video urls')

videoprefix = xmldoc.get('videoPrefix')


listofvideotags = xmldoc.findall('.//imageBox')
videos = []

for videotag in listofvideotags:
    videos.append(videotag.get('videoHiRes'))

for video_url in videos:
	
        video_url_real = "%s%s" % (videoprefix, video_url)
	
	print video_url_real

	video_filename = video_url_real.split('/')[-1]
	
	download_video_step(video_filename, video_url_real)

# Finish
sys.exit()

