#!/usr/bin/env python
# Copyright Lee Begg 2009
#
# NZ Herald video download tool
#
# Borrowing heavily from youtube-dl


import sys
import re
from xml.etree import ElementTree as ET
from viddl.steps import download_step, extract_step, http_download_video_step

const_smilfile_re = re.compile(r"playlist: '([^']+)',")
const_smilfile_url_fmt = "http://tvnz.co.nz%s"



if(len(sys.argv) > 1):
    req_url = sys.argv[1]
    
else:
    print("Usage: %s url" % sys.argv[0])
    sys.exit(1)
    

#should check url first
video_url = req_url

video_webpage = download_step(True, 'Retrieving video webpage', 'unable to retrieve video webpage', video_url)

smilfilestr = extract_step('Extracting SMIL playlist url', 'unabled to extract SMIL playlist url', const_smilfile_re, video_webpage)

smilfileurl = const_smilfile_url_fmt % smilfilestr

smil_file = download_step(True, 'Retrieving SMIL playlist', 'unable to retrieve SMIL playlist', smilfileurl)

print('Parsing SMIL')

smildoc = ET.fromstring(smil_file)

print('Extracting video urls')

listofvideotags = smildoc.findall('.//{http://www.w3.org/ns/SMIL}video')
videos = []

for videotag in listofvideotags:
	if videotag.get('systemBitrate') == '700000':
		videos.append(videotag.get('src'))

for video_url_real in videos:
	
	
	print video_url_real

	video_filename = video_url_real.split('/')[-1]
	
	http_download_video_step(video_filename, video_url_real)

# Finish
sys.exit()

